/**
 * Generate dist/sw.js after the Astro build.
 *
 * The precache list is derived from the actual build output, so hashed asset
 * filenames are always correct and a stale service worker can never pin an
 * asset that no longer exists. The cache name embeds a hash of that list, so
 * any content change produces a new cache and the old one is evicted on
 * activate.
 *
 * Run via `npm run build` (astro build && node scripts/generate-sw.mjs).
 */
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const dist = path.join(root, 'dist')

if (!fs.existsSync(dist)) {
  console.error('generate-sw: dist/ not found — run astro build first')
  process.exit(1)
}

/** Everything worth having offline. Excludes things only crawlers read. */
const EXCLUDE = new Set(['/sw.js', '/sitemap-index.xml', '/sitemap-0.xml', '/robots.txt', '/CNAME'])

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name)
    return e.isDirectory() ? walk(full) : [full]
  })
}

const urls = walk(dist)
  .map((f) => '/' + path.relative(dist, f).split(path.sep).join('/'))
  // /foo/index.html is requested as /foo/ — cache the URL the browser asks for.
  .map((u) => (u.endsWith('/index.html') ? u.slice(0, -'index.html'.length) : u))
  .filter((u) => !EXCLUDE.has(u))
  .sort()

const version = crypto.createHash('sha256').update(urls.join('\n')).digest('hex').slice(0, 12)

const sw = `// Generated by scripts/generate-sw.mjs — do not edit.
const CACHE = 'intech-${version}'
const PRECACHE = ${JSON.stringify(urls, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  )
})

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return // never touch cross-origin

  // Pages: network first, so a fresh deploy is picked up immediately, with the
  // cache standing in when offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((res) => {
          const copy = res.clone()
          caches.open(CACHE).then((c) => c.put(request, copy))
          return res
        })
        .catch(() =>
          caches.match(request).then((hit) => hit || caches.match('/404.html') || caches.match('/'))
        )
    )
    return
  }

  // Assets are content-hashed, so cache first is safe and instant.
  event.respondWith(
    caches.match(request).then(
      (hit) =>
        hit ||
        fetch(request).then((res) => {
          if (res.ok) {
            const copy = res.clone()
            caches.open(CACHE).then((c) => c.put(request, copy))
          }
          return res
        })
    )
  )
})
`

fs.writeFileSync(path.join(dist, 'sw.js'), sw)
console.log(`  sw.js written — cache intech-${version}, ${urls.length} precached URLs`)
for (const u of urls) console.log(`    ${u}`)
