/**
 * Generates the whole favicon set from one tracked source.
 *
 * This used to read public/favicon.svg — a file that was never committed. The
 * PNGs in public/ were produced from it once and could not be regenerated by
 * anyone who cloned the repo, including on CI. Sourcing from src/assets/mark.png
 * (tracked, 512x512) makes the set reproducible. If a real vector of the mark
 * turns up, drop it in as public/favicon.svg and it is preferred automatically —
 * it rasterises more cleanly at 16 and 32 px than any downscale can.
 *
 * Uses the sharp that ships with Astro, so there is no extra dependency.
 * Run with: npm run icons
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))

const svgPath = path.join(root, 'public', 'favicon.svg')
const pngPath = path.join(root, 'src', 'assets', 'mark.png')

const usingSvg = fs.existsSync(svgPath)
const src = fs.readFileSync(usingSvg ? svgPath : pngPath)
// density only means anything for SVG input; sharp ignores it for raster.
const load = () => sharp(src, usingSvg ? { density: 384 } : {})

console.log(`  source: ${usingSvg ? 'public/favicon.svg' : 'src/assets/mark.png'}\n`)

const targets = [
  { file: 'favicon-16.png', size: 16 }, // browser tab
  { file: 'favicon-32.png', size: 32 }, // browser tab, retina
  { file: 'apple-touch-icon.png', size: 180 }, // iOS home screen
  { file: 'icon-192.png', size: 192 }, // PWA manifest
  { file: 'icon-512.png', size: 512 }, // PWA splash / install prompt
]

for (const { file, size } of targets) {
  const out = path.join(root, 'public', file)
  await load().resize(size, size).png({ compressionLevel: 9 }).toFile(out)
  console.log(`  ${file.padEnd(22)} ${size}x${size}  ${fs.statSync(out).size.toLocaleString()} B`)
}

/* favicon.ico — for the bare /favicon.ico that browsers, crawlers, feed readers
   and link-preview bots request whether or not any <link> points at it. Without
   it that request is a 404 on every cold visit.

   Written by hand because sharp has no .ico encoder. The format is a small
   directory followed by the images; since Vista those images may be PNGs
   rather than BMPs, which is what every modern generator emits. */
{
  const sizes = [16, 32, 48]
  const pngs = []
  for (const size of sizes) {
    pngs.push(await load().resize(size, size).png({ compressionLevel: 9 }).toBuffer())
  }

  const HEADER = 6
  const ENTRY = 16
  const header = Buffer.alloc(HEADER)
  header.writeUInt16LE(0, 0) // reserved
  header.writeUInt16LE(1, 2) // 1 = icon (2 would be cursor)
  header.writeUInt16LE(sizes.length, 4)

  // Image data starts after the header and every directory entry.
  let offset = HEADER + ENTRY * sizes.length
  const entries = sizes.map((size, i) => {
    const e = Buffer.alloc(ENTRY)
    // 0 means 256 in this field, which is why it is a single byte.
    e.writeUInt8(size === 256 ? 0 : size, 0)
    e.writeUInt8(size === 256 ? 0 : size, 1)
    e.writeUInt8(0, 2) // palette size; 0 for truecolour
    e.writeUInt8(0, 3) // reserved
    e.writeUInt16LE(1, 4) // colour planes
    e.writeUInt16LE(32, 6) // bits per pixel
    e.writeUInt32LE(pngs[i].length, 8)
    e.writeUInt32LE(offset, 12)
    offset += pngs[i].length
    return e
  })

  const out = path.join(root, 'public', 'favicon.ico')
  fs.writeFileSync(out, Buffer.concat([header, ...entries, ...pngs]))
  console.log(
    `  ${'favicon.ico'.padEnd(22)} ${sizes.join('/')}  ${fs.statSync(out).size.toLocaleString()} B`
  )
}

// Maskable icon: Android crops home-screen icons to arbitrary shapes and only
// guarantees the middle ~80%. Inset the mark on a full-bleed background so the
// corners can be clipped without eating the letters.
{
  const size = 512
  const inner = Math.round(size * 0.62)
  const pad = Math.round((size - inner) / 2)
  const out = path.join(root, 'public', 'icon-maskable-512.png')
  const mark = await load().resize(inner, inner).png().toBuffer()
  await sharp({
    create: { width: size, height: size, channels: 4, background: '#1f6feb' },
  })
    .composite([{ input: mark, top: pad, left: pad }])
    .png({ compressionLevel: 9 })
    .toFile(out)
  console.log(`  ${'icon-maskable-512.png'.padEnd(22)} ${size}x${size}  ${fs.statSync(out).size.toLocaleString()} B`)
}
